version: '3'

services:
  redis:
    container_name: redis-kata
    hostname: redis
    image: redis:6.2.5
    ports:
      - "16379:6379"

  redis-commander:
    container_name: redis-commander-kata
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8881:8081"
